name: build and test

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: build with gradle
      env:
        TEST_ECO_UFPEL_DATABASE_IP: ${{ secrets.TEST_ECO_UFPEL_DATABASE_IP }}
        TEST_ECO_UFPEL_DATABASE_PORT: ${{ secrets.TEST_ECO_UFPEL_DATABASE_PORT }}
        TEST_ECO_UFPEL_DATABASE_NAME: ${{ secrets.TEST_ECO_UFPEL_DATABASE_NAME }}
        TEST_ECO_UFPEL_DATABASE_USER: ${{ secrets.TEST_ECO_UFPEL_DATABASE_USER }}
        TEST_ECO_UFPEL_DATABASE_PASSWORD: ${{ secrets.TEST_ECO_UFPEL_DATABASE_PASSWORD }}
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
