name: build, test and deploy

on:
  push:
    branches: [ "main" , "ci-cd" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Database_test_settings

    steps:
    - uses: actions/checkout@v3
    - name: setup JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: build with gradle
      env:
        TEST_ECO_UFPEL_DATABASE_IP: ${{ secrets.Database_test_settings.TEST_ECO_UFPEL_DATABASE_IP }}
        TEST_ECO_UFPEL_DATABASE_PORT: ${{ secrets.Database_test_settings.TEST_ECO_UFPEL_DATABASE_PORT }}
        TEST_ECO_UFPEL_DATABASE_NAME: ${{ secrets.Database_test_settings.TEST_ECO_UFPEL_DATABASE_NAME }}
        TEST_ECO_UFPEL_DATABASE_USER: ${{ secrets.Database_test_settings.TEST_ECO_UFPEL_DATABASE_USER }}
        TEST_ECO_UFPEL_DATABASE_PASSWORD: ${{ secrets.Database_test_settings.TEST_ECO_UFPEL_DATABASE_PASSWORD }}
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build


    - name: build & push docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: gustavohroos/ecoufpel-backend
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
